# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_musictrackpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictrackpage',
            name='track',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailcore.blocks.StreamBlock(())),), default=''),
            preserve_default=False,
        ),
    ]
