# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 10:55
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20171214_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictrackpage',
            name='track',
            field=wagtail.wagtailcore.fields.StreamField((('video', wagtail.wagtailembeds.blocks.EmbedBlock()),)),
        ),
    ]
